[project]
name = "ni-house-prices"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "geopandas>=0.11.1",
    "ipython>=9.6.0",
    "lxml>=6.0.2",
    "matplotlib>=3.10.6",
    "numpy>=1.24.4",
    "pandera>=0.27.1",
    "psutil>=7.1.0",
    "requests>=2.32.5",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "statsmodels>=0.13.2",
]
